CREATE DATABASE GSMDB;
USE GSMDB;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

SELECT 
    *
FROM
    SUPPLIER;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
SELECT 
    *
FROM
    categories;

TRUNCATE TABLE categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

SELECT 
    *
FROM
    EMPLOYEES;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

SELECT 
    *
FROM
    CUSTOMERS;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10 , 2 ),
    FOREIGN KEY (sup_id)
        REFERENCES supplier (sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id)
        REFERENCES categories (cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT 
    *
FROM
    PRODUCTS;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id)
        REFERENCES customers (cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id)
        REFERENCES employees (emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT 
    *
FROM
    ORDERS;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10 , 2 ),
    total_price DECIMAL(10 , 2 ),
    FOREIGN KEY (ord_id)
        REFERENCES orders (ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id)
        REFERENCES products (prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

SELECT 
    *
FROM
    ORDER_DETAILS;

-- 1️. Customer Insights
-- HOW MANY UNIQUE CUSTOMERS HAVE PALACED ORDERS?
SELECT 
    COUNT(DISTINCT cust_id) AS unique_customers
FROM
    orders;

-- WHICH CUSTOMERS HAVE PLACED THE HIGHEST NUMBER OF ORDERS?
SELECT 
    c.cust_id, c.cust_name, COUNT(o.ord_id) AS total_orders
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id , c.cust_name
ORDER BY total_orders DESC;

-- WHAT IS THE TOTAL AND AVERAGE PURCHASE VALUE PER CUSTOMER?
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase_value,
    AVG(od.total_price) AS avg_purchase_value
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id , c.cust_name;

-- WHO ARE THE TOP 5 CUSTOMERS BY TOTAL PURCAHSE AMOUNT?
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase_amount
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id , c.cust_name
ORDER BY total_purchase_amount DESC
LIMIT 5;

-- 2. Product Performance
-- How many products exist in each category?
SELECT 
    c.cat_id, c.cat_name, COUNT(p.prod_id) AS total_products
FROM
    categories c
        LEFT JOIN
    products p ON c.cat_id = p.cat_id
GROUP BY c.cat_id , c.cat_name
ORDER BY total_products DESC;

-- What is the average price of products by category?
SELECT 
    c.cat_id,
    c.cat_name,
    ROUND(AVG(p.price), 2) AS avg_product_price
FROM
    categories c
        JOIN
    products p ON c.cat_id = p.cat_id
GROUP BY c.cat_id , c.cat_name
ORDER BY avg_product_price DESC;

-- Which products have the highest total sales volume (by quantity)?
SELECT 
    p.prod_id,
    p.prod_name,
    SUM(od.quantity) AS total_quantity_sold
FROM
    products p
        JOIN
    order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id , p.prod_name
ORDER BY total_quantity_sold DESC;

-- What is the total revenue generated by each product?
SELECT 
    p.prod_id,
    p.prod_name,
    ROUND(SUM(od.total_price), 2) AS total_revenue
FROM
    products p
        JOIN
    order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id , p.prod_name
ORDER BY total_revenue DESC;

-- How do product sales vary by category and supplier?
SELECT 
    c.cat_name,
    s.sup_name,
    SUM(od.quantity) AS total_quantity_sold,
    ROUND(SUM(od.total_price), 2) AS total_sales_value
FROM
    order_details od
        JOIN
    products p ON od.prod_id = p.prod_id
        JOIN
    categories c ON p.cat_id = c.cat_id
        JOIN
    supplier s ON p.sup_id = s.sup_id
GROUP BY c.cat_name , s.sup_name
ORDER BY total_sales_value DESC;

-- 3. Sales and Order Trends
-- How many orders have been placed in total?
SELECT 
    COUNT(*) AS total_orders
FROM
    orders;

-- What is the average value per order?
SELECT 
    AVG(order_total) AS avg_order_value
FROM
    (SELECT 
        ord_id, SUM(total_price) AS order_total
    FROM
        order_details
    GROUP BY ord_id) AS order_summary;

-- On which dates were the most orders placed?
SELECT 
    order_date, COUNT(ord_id) AS total_orders
FROM
    orders
GROUP BY order_date
ORDER BY total_orders DESC;

-- What are the monthly trends in orer volume and revenue?
SELECT 
    DATE_FORMAT(STR_TO_DATE(o.order_date, '%Y-%m-%d'),
            '%Y-%m') AS order_month,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue
FROM
    orders o
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY order_month
ORDER BY order_month;

-- How do order patterns vary across weekdays and weekends?
SELECT 
    CASE
        WHEN DAYOFWEEK(STR_TO_DATE(o.order_date, '%Y-%m-%d')) IN (1 , 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(DISTINCT o.ord_id) AS order_volume,
    SUM(od.total_price) AS total_revenue
FROM
    orders o
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY day_type;

-- 4️. Supplier Contribution
-- How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- Which supplier provides the most products?
SELECT 
    s.sup_id,
    s.sup_name,
    COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p 
    ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_products DESC;

-- What is the average price of products from each supplier?
SELECT 
    s.sup_id,
    s.sup_name,
    ROUND(AVG(p.price), 2) AS avg_product_price
FROM supplier s
JOIN products p 
    ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY avg_product_price DESC;

-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT 
    s.sup_id,
    s.sup_name,
    ROUND(SUM(od.total_price), 2) AS total_revenue
FROM supplier s
JOIN products p 
    ON s.sup_id = p.sup_id
JOIN order_details od 
    ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;

-- 5️. Employee Performance
-- How many employees have processed orders?
SELECT 
    COUNT(DISTINCT emp_id) AS employees_with_orders
FROM
    orders;

-- Which employees have handled the most orders?
SELECT 
    e.emp_id,
    e.emp_name,
    COUNT(o.ord_id) AS total_orders_handled
FROM employees e
JOIN orders o 
    ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_orders_handled DESC;

-- What is the total sales value processed by each employee?
SELECT 
    e.emp_id,
    e.emp_name,
    ROUND(SUM(od.total_price), 2) AS total_sales_value
FROM employees e
JOIN orders o 
    ON e.emp_id = o.emp_id
JOIN order_details od 
    ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales_value DESC;

-- What is the average order value handled per employee?
SELECT 
    e.emp_id,
    e.emp_name,
    ROUND(AVG(order_total), 2) AS avg_order_value
FROM employees e
JOIN (
    SELECT 
        o.emp_id,
        o.ord_id,
        SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od 
        ON o.ord_id = od.ord_id
    GROUP BY o.emp_id, o.ord_id
) AS order_summary
ON e.emp_id = order_summary.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;

-- 6️. Order Details Deep Dive
-- What is the relationship between quantity ordered and total price?
SELECT 
    quantity, ROUND(AVG(total_price), 2) AS avg_total_price
FROM
    order_details
GROUP BY quantity
ORDER BY quantity;

-- What is the average quantity ordered per product?
SELECT 
    p.prod_id,
    p.prod_name,
    ROUND(AVG(od.quantity), 2) AS avg_quantity_ordered
FROM products p
JOIN order_details od 
    ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_quantity_ordered DESC;

-- How does the unit price vary across products and orders?
SELECT 
    p.prod_name,
    COUNT(od.ord_id) AS total_orders,
    MIN(od.each_price) AS minimum_price,
    MAX(od.each_price) AS maximum_price,
    AVG(od.each_price) AS average_price
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
GROUP BY p.prod_name
ORDER BY average_price DESC;

























